### ISSUE TITLE
Include entity definitions (entity labels)

### ISSUE THREAD

**Issue by CotterpinDoozer** [CancerRegistryOfNorway/nordcanpreprocessing#33]
This page https://metadata.kreftregisteret.no/variables/detail/814?tabIndex=4 contains an overview of the entity descriptions/labels for all entities used in NORDCAN. An xls-file can be downloaded from this site to be used in ELVIS - needs to be updated before each new version. 

The English names of the entities should be available in nordcan.R - both on request and, for instance, when we export the comparison graphs, so that it for instance says "90: colon" instead of just "90".

**Comment by CotterpinDoozer** [comment]
Issue: Include entity definitions (entity labels)
Comment: need to talk with Siri. Estimate time: 1+ hours

**Comment by CotterpinDoozer** [comment]
We wish for labels for each entity for these files: 
* cancer_death_count_dataset_vx.x_vs_vt.png
* cancer_record_count_dataset_vx.x_vs_vt.png
* prevalent_patient_count_dataset_vx.x_vs_vt.png

**Comment by CotterpinDoozer** [comment]
Something to consider: entities and labels might change over time. How to keep this updated with a minimum of manual work?

**Comment by CotterpinDoozer** [comment]
We might have some problems here with the length of the descriptions, and we need to discuss how to handle this. 
The file needs to be attached to nordcan.R. 

How to keep it updated: store as csv-file and use version control to track the changes.

**Comment by HuidongTian** [comment]
Updated. 

- add the **entity_label.csv** as package data of **nordcancore**
- change **png** format to **pdf** format, which provides cleaner figure
- drop repeated x-axis and y-axis labels for saving plotting space.
- include full-label for each entity item by using multiple-line title.
- add the file name as the main title, so users can easily distinguish the printed comparison figure.

https://github.com/CancerRegistryOfNorway/nordcancore/blob/master/data-raw/entity_label.csv
https://github.com/CancerRegistryOfNorway/nordcanepistats/blob/master/R/compare_statistics_tables.R#L397

**Comment by AnnaSkog** [comment]
We must remember to change the heading in nordcan.R from "## Plot the comparison in figures (.png)." to "## Plot the comparison in figures (.jpg)."
